### ISSUE TITLE
Ignoring exception in on_ready

### ISSUE THREAD

**Issue by WrongProgram1** [Sp00p64/DiscordRAT#13]
....

**Comment by WrongProgram1** [comment]
or do I use "!interact <uuid>"

**Comment by WrongProgram1** [comment]
I also got Identation Error

**Comment by WrongProgram1** [comment]
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MyPC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\MyPC\Documents\Coding Stuffs\Python\DiscordRAT-master\DiscordRAT(WithCV).py", line 63, in on_ready
    with urllib.request.urlopen("https://geolocation-db.com/json") as url:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11004] getaddrinfo failed>
```

**Comment by Sp00p64** [comment]
The program is crashing during a urllib resquest which could indicates a problem or misconfiguration with your internet connection.I suggest you to check if you're under any proxy.
