### ISSUE TITLE
Error with bot + uninstallation

### ISSUE THREAD

**Issue by ReggaeBoi** [Sp00p64/DiscordRAT#27]
Hey, recently tried to run DiscordRAT.py and got this error:
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\jacka\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "DiscordRAT.py", line 71, in on_ready
    newchannel = await client.guilds[0].create_text_channel(uuidgen)
  File "C:\Users\jacka\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\discord\guild.py", line 948, in create_text_channel
    data = await self._create_channel(name, overwrites, ChannelType.text, category, reason=reason, **options)
  File "C:\Users\jacka\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\discord\http.py", line 248, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
Is there a current fix to this problem?

Also, how exactly do I uninstall the RAT?

Any help appreciated!

**Comment by Sp00p64** [comment]
As the error entails, the bot is missing permissions, you need to go to the bot management page and add administrator permissions.
And if by "uninstalling" you mean delete of a server, just kick the bot from the server you added it in.
