### ISSUE TITLE
cant exe

### ISSUE THREAD

**Issue by Arwy17** [Sp00p64/DiscordRAT#30]
Hello, I have problem, here is how it responded

73 INFO: PyInstaller: 4.3
73 INFO: Python: 3.8.0
74 INFO: Platform: Windows-10-10.0.19041-SP0
75 INFO: wrote C:\Users\Arwy\Downloads\DiscordRAT-master\DiscordRAT-master\DiscordRAT.spec
76 INFO: UPX is not available.
77 INFO: Extending PYTHONPATH with paths
['C:\\Users\\Arwy\\Downloads\\DiscordRAT-master\\DiscordRAT-master',
 'C:\\Users\\Arwy\\Downloads\\DiscordRAT-master\\DiscordRAT-master']
101 INFO: checking Analysis
101 INFO: Building Analysis because Analysis-00.toc is non existent
101 INFO: Initializing module dependency graph...
103 INFO: Caching module graph hooks...
112 WARNING: Several hooks defined for module 'win32ctypes.core'. Please take care they do not conflict.
119 INFO: Analyzing base_library.zip ...
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "c:\users\arwy\appdata\local\programs\python\python38\lib\traceback.py", line 5, in <module>
    import linecache
  File "c:\users\arwy\appdata\local\programs\python\python38\lib\linecache.py", line 11, in <module>
    import tokenize
  File "c:\users\arwy\appdata\local\programs\python\python38\lib\tokenize.py", line 32, in <module>
    import re
  File "c:\users\arwy\appdata\local\programs\python\python38\lib\re.py", line 143, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "c:\users\arwy\appdata\local\programs\python\python38\lib\traceback.py", line 5, in <module>
    import linecache
  File "c:\users\arwy\appdata\local\programs\python\python38\lib\linecache.py", line 11, in <module>
    import tokenize
  File "c:\users\arwy\appdata\local\programs\python\python38\lib\tokenize.py", line 32, in <module>
    import re
  File "c:\users\arwy\appdata\local\programs\python\python38\lib\re.py", line 143, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
2945 INFO: Caching module dependency graph...
3027 INFO: running Analysis Analysis-00.toc
3035 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\arwy\appdata\local\programs\python\python38\python.exe
3105 INFO: Analyzing C:\Users\Arwy\Downloads\DiscordRAT-master\DiscordRAT-master\DiscordRAT.py
4977 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from 'c:\\users\\arwy\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-urllib3.packages.six.moves.py'.
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "c:\users\arwy\appdata\local\programs\python\python38\lib\site-packages\urllib3\__init__.py", line 7, in <module>
    import logging
  File "c:\users\arwy\appdata\local\programs\python\python38\lib\logging\__init__.py", line 26, in <module>
    import sys, os, time, io, re, traceback, warnings, weakref, collections.abc
  File "c:\users\arwy\appdata\local\programs\python\python38\lib\re.py", line 143, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
pre-safe-import-module hook failed, needs fixing.

**Comment by Arwy17** [comment]
okay i fixed it, sr i forget on last part on code page
