### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Err0r-C0de** [Sp00p64/DiscordRAT#32]
If I run the .exe file in a VM it shows a Fatal Error failed to execute script
![Screenshot_1](https://user-images.githubusercontent.com/84100446/118315565-f710e980-b4f5-11eb-981f-4f39d55f187a.png)

**Comment by Sp00p64** [comment]
Does the program run properly without being compiled ?

**Comment by TQMatvey** [comment]
C:\Users\mmat0\Desktop>python DiscordRAT.py
Traceback (most recent call last):
  File "C:\Users\mmat0\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\http.py", line 300, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\mmat0\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "DiscordRAT.py", line 563, in <module>
    client.run(token)
  File "C:\Users\mmat0\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 723, in run
    return future.result()
  File "C:\Users\mmat0\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 702, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\mmat0\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 665, in start
    await self.login(*args, bot=bot)
  File "C:\Users\mmat0\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 511, in login
    await self.http.static_login(token.strip(), bot=bot)
  File "C:\Users\mmat0\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\http.py", line 304, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000019668C34310>
Traceback (most recent call last):
  File "C:\Users\mmat0\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\mmat0\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\mmat0\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Users\mmat0\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by Sp00p64** [comment]
This problem is unrelated to this issue please open a new one.
And you get this issue because your token is either invalid or because it's missing administrator permissions

**Comment by Sp00p64** [comment]
Closing this issue for now
