### ISSUE TITLE
Having Trouble Installing Requirements

### ISSUE THREAD

**Issue by TacticzONG** [Sp00p64/DiscordRAT#43]
Everytime I try to run the requirements in terminal or cmd prompt, it tells me "Traceback (most recent call last):
  File "c:\users\doopd\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main   
    return _run_code(code, main_globals, None,
  File "c:\users\doopd\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\doopd\AppData\Local\Programs\Python\Python39\Scripts\pip3.exe\__main__.py", line 4, in <module>
  File "c:\users\doopd\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\cli\main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "c:\users\doopd\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "c:\users\doopd\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\cli\main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "c:\users\doopd\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\cli\cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "c:\users\doopd\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\cli\parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "c:\users\doopd\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\configuration.py", line 27, in <module>
    from pip._internal.utils.misc import ensure_dir, enum
  File "c:\users\doopd\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\utils\misc.py", line 38, in <module>
    from pip._vendor.tenacity import retry, stop_after_delay, wait_fixed
  File "c:\users\doopd\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 522, in <module>
    from pip._vendor.tenacity._asyncio import AsyncRetrying
  File "c:\users\doopd\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\tenacity\_asyncio.py", line 19, in <module>
    from asyncio import sleep
  File "c:\users\doopd\appdata\local\programs\python\python39\lib\asyncio\__init__.py", line 43, in <module>
    from .windows_events import *
  File "c:\users\doopd\appdata\local\programs\python\python39\lib\asyncio\windows_events.py", line 304, in <module>
    class ProactorEventLoop(proactor_events.BaseProactorEventLoop):
AttributeError: module 'asyncio.proactor_events' has no attribute 'BaseProactorEventLoop''

Can you guys please help me?

**Comment by TacticzONG** [comment]
oops i am so sory
