### ISSUE TITLE
Everytime I run the code

### ISSUE THREAD

**Issue by TacticzONG** [Sp00p64/DiscordRAT#44]
Everytime i run the code in pycharm i see this

Traceback (most recent call last):
  File "C:\Users\doopd\PycharmProjects\DiscordRAT\venv\lib\site-packages\discord\http.py", line 300, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\doopd\PycharmProjects\DiscordRAT\venv\lib\site-packages\discord\http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\doopd\PycharmProjects\DiscordRAT\DisordRAT.py", line 589, in <module>
    client.run(token)
  File "C:\Users\doopd\PycharmProjects\DiscordRAT\venv\lib\site-packages\discord\client.py", line 723, in run
    return future.result()
  File "C:\Users\doopd\PycharmProjects\DiscordRAT\venv\lib\site-packages\discord\client.py", line 702, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\doopd\PycharmProjects\DiscordRAT\venv\lib\site-packages\discord\client.py", line 665, in start
    await self.login(*args, bot=bot)
  File "C:\Users\doopd\PycharmProjects\DiscordRAT\venv\lib\site-packages\discord\client.py", line 511, in login
    await self.http.static_login(token.strip(), bot=bot)
  File "C:\Users\doopd\PycharmProjects\DiscordRAT\venv\lib\site-packages\discord\http.py", line 304, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000209FF4EED30>
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Program Files\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

Process finished with exit code 1

What do I do because im new to this and i need help?

**Comment by Sp00p64** [comment]
You are missing permissions for your discord bot.Please add administrator permissions

**Comment by Laar-u** [comment]
> 
> 
> You are missing permissions for your discord bot.Please add administrator permissions

i believe this is a invalid token actually, cause if you see the 2nd link from the top at the end of it it says "static_login" and next line it tries to get the /users/@me endpoint, which returns unauthorized.

**Comment by TacticzONG** [comment]
I did give my bot admin and everything but it still says the same thing.

**Comment by TacticzONG** [comment]
Its not invalid because i regenerated a new one and it says the same thing.
