### ISSUE TITLE
IndexError : list index out of range

### ISSUE THREAD

**Issue by SuperMoke** [Sp00p64/DiscordRAT#55]
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\Marc\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Marc\Desktop\Discord-RAT-main\DiscordRAT.py", line 107, in on_ready
    newchannel = await client.guilds[0].create_text_channel(channel_name)
IndexError: list index out of range

**Comment by Sp00kySkelet0n** [comment]
Could you give me your python version ?
