### ISSUE TITLE
error pls help

### ISSUE THREAD

**Issue by GipiXETH** [Sp00p64/DiscordRAT#73]
C:\Users\gipix\Desktop>python DiscordRAT.py
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\gipix\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\gipix\Desktop\DiscordRAT.py", line 141, in on_ready
    biggest = max(map(int, result))
ValueError: max() arg is an empty sequence

**Comment by euclidsss** [comment]
its cuz u have python 3.10
